export const CAREER_GROUPS: Record<string, string[]> = {
  Engineering: [
    "Software Engineer",
    "Frontend Engineer",
    "Backend Engineer",
    "Full Stack Engineer",
    "Mobile Engineer",
    "Data Engineer",
    "DevOps Engineer",
    "Cloud Engineer",
    "Security Engineer",
  ],
  "Data & Analytics": [
    "Data Science",
    "Data Analyst",
    "Business Analyst",
    "Analytics Engineer",
  ],
  "Product & Design": [
    "Product Management",
    "Product Design",
    "UX Design",
    "UI Design",
  ],
  "Finance & Trading": [
    "Quant/Trading",
    "Finance",
    "Investment Banking",
  ],
  Business: [
    "Consulting",
    "Strategy",
    "Operations",
    "Marketing",
    "Sales",
    "Business Development",
  ],
  "STEM & Research": [
    "Biomedical Engineer",
    "Bioengineer",
    "Biochemist",
    "Biophysicist",
    "Chemist",
    "Physicist",
    "Research Scientist",
    "Lab Technician",
    "Clinical Research Associate",
    "Pharmaceutical Scientist",
    "Materials Scientist",
    "Environmental Scientist",
    "Computational Biologist",
    "Geneticist",
    "Molecular Biologist",
    "Pharmacologist",
  ],
  "Healthcare & Medicine": [
    "Doctor",
    "Physician",
    "Surgeon",
    "Primary Care Physician",
    "Emergency Medicine Physician",
    "Pediatrician",
    "Cardiologist",
    "Oncologist",
    "Neurologist",
    "Psychiatrist",
    "Anesthesiologist",
    "Radiologist",
    "Dermatologist",
    "Orthopedic Surgeon",
    "Nurse",
    "Nurse Practitioner",
    "Physician Assistant",
    "Medical Researcher",
    "Clinical Trial Specialist",
    "Medical Writer",
  ],
  Other: ["Other"],
};

export const CAREER_DESCRIPTIONS: Record<string, string> = {
  "Software Engineer": "Build and maintain software applications and systems",
  "Frontend Engineer": "Create user interfaces and interactive web experiences",
  "Backend Engineer": "Develop server-side logic, APIs, and databases",
  "Full Stack Engineer": "Work across both frontend and backend development",
  "Mobile Engineer": "Develop iOS, Android, or cross-platform mobile apps",
  "Data Engineer": "Design and build data pipelines and infrastructure",
  "DevOps Engineer": "Automate deployment, scaling, and monitoring",
  "Cloud Engineer": "Architect and manage cloud infrastructure",
  "Security Engineer": "Protect systems and applications from threats",
  "Data Science": "Analyze data to extract insights and build ML models",
  "Data Analyst": "Turn data into actionable business insights",
  "Business Analyst": "Bridge business needs with technical solutions",
  "Analytics Engineer": "Build and maintain data analytics infrastructure",
  "Product Management": "Define product vision and guide development",
  "Product Design": "Design user experiences and interfaces",
  "UX Design": "Create intuitive and user-centered designs",
  "UI Design": "Design visual interfaces and design systems",
  "Quant/Trading": "Develop quantitative trading strategies and models",
  "Finance": "Manage financial planning, analysis, and operations",
  "Investment Banking": "Facilitate M&A, IPOs, and capital raising",
  "Consulting": "Advise organizations on strategy and operations",
  "Strategy": "Develop long-term strategic plans and initiatives",
  "Operations": "Optimize business processes and efficiency",
  "Marketing": "Drive brand awareness and customer acquisition",
  "Sales": "Build relationships and close deals",
  "Business Development": "Identify and pursue growth opportunities",
  "Biomedical Engineer": "Design medical devices and biological systems",
  "Bioengineer": "Apply engineering principles to biological systems",
  "Biochemist": "Study chemical processes in living organisms",
  "Biophysicist": "Apply physics principles to biological systems",
  "Chemist": "Research and develop chemical processes and materials",
  "Physicist": "Research physical properties and phenomena",
  "Research Scientist": "Conduct research and experiments in scientific fields",
  "Lab Technician": "Perform laboratory tests and experiments",
  "Clinical Research Associate": "Manage clinical trials and research studies",
  "Pharmaceutical Scientist": "Develop and test pharmaceutical drugs",
  "Materials Scientist": "Research and develop new materials",
  "Environmental Scientist": "Study environmental systems and solutions",
  "Computational Biologist": "Apply computational methods to biological problems",
  "Geneticist": "Study genes, heredity, and genetic variation",
  "Molecular Biologist": "Study biological processes at molecular level",
  "Pharmacologist": "Research effects of drugs and medicines",
  "Doctor": "Diagnose and treat medical conditions",
  "Physician": "Provide medical care and treatment to patients",
  "Surgeon": "Perform surgical procedures to treat conditions",
  "Primary Care Physician": "Provide comprehensive primary healthcare",
  "Emergency Medicine Physician": "Treat patients in emergency settings",
  "Pediatrician": "Provide medical care for infants, children, and adolescents",
  "Cardiologist": "Diagnose and treat heart and cardiovascular conditions",
  "Oncologist": "Diagnose and treat cancer",
  "Neurologist": "Diagnose and treat neurological disorders",
  "Psychiatrist": "Diagnose and treat mental health disorders",
  "Anesthesiologist": "Administer anesthesia during surgical procedures",
  "Radiologist": "Interpret medical imaging studies",
  "Dermatologist": "Diagnose and treat skin conditions",
  "Orthopedic Surgeon": "Perform surgery on musculoskeletal system",
  "Nurse": "Provide patient care and medical support",
  "Nurse Practitioner": "Provide advanced nursing care and treatment",
  "Physician Assistant": "Assist physicians in medical care and procedures",
  "Medical Researcher": "Conduct research in medical and healthcare fields",
  "Clinical Trial Specialist": "Manage and coordinate clinical trials",
  "Medical Writer": "Create medical documentation and content",
};

